apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: node-app
spec:
  type: LoadBalancer   # <--- changed here
  selector:
    app: node-app
  ports:
  - port: 80           # external port (what the LB will expose)
    targetPort: 3000   # port inside your Pod
